apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-service
  namespace: argocd
spec:
    source:
      targetRevision: HEAD
      helm:
        valueFiles:
        - values/development/values.yaml
    syncPolicy:
      automated: { }
